import { Alert, AlertDescription } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Field } from "@/components/ui/field";
import { Input } from "@/components/ui/input";
import { cn } from "@/lib/utils";

function AuthHeroPanel() {
  return (
    <div className="border-b border-border bg-muted/30 p-8 lg:border-r lg:border-b-0 lg:p-10">
      <p className="text-xs font-semibold uppercase tracking-widest text-muted-foreground">
        SpicyTrack
      </p>
      <h1 className="mt-4 text-4xl font-semibold tracking-tight">
        Sentry-compatible.
        <br />
        Source available.
        <br />
        Multi-tenant.
      </h1>
      <p className="mt-6 max-w-xl text-sm leading-7 text-muted-foreground">
        The frontend consumes hooks generated by Orval from the backend&apos;s OpenAPI spec, keeping
        the API contract tight and verifiable.
      </p>
    </div>
  );
}

function AuthModePanel({
  mode,
  switchMode,
  forgotSent,
  error,
  isPending,
  onSubmit,
  onSsoSignIn,
  passwordEnabled,
  registrationsEnabled,
  sso,
}: {
  mode: "login" | "register" | "forgot";
  switchMode: (nextMode: "login" | "register" | "forgot") => void;
  forgotSent: boolean;
  error: string | null;
  isPending: boolean;
  onSubmit: React.FormEventHandler<HTMLFormElement>;
  onSsoSignIn: (providerId: string) => void;
  passwordEnabled: boolean;
  registrationsEnabled: boolean;
  sso: { providerId: string; providerName: string } | null;
}) {
  return (
    <div className="p-8 lg:p-10">
      <CardHeader className="p-0">
        <CardTitle className="text-2xl tracking-tight">
          {mode === "login"
            ? "Sign in"
            : mode === "register"
              ? "Create your account"
              : "Forgot password"}
        </CardTitle>
        <CardDescription>
          {mode === "forgot"
            ? "Enter your email and we'll send you a reset link if an account exists."
            : "Organizations and projects become visible once you sign in."}
        </CardDescription>
      </CardHeader>

      <CardContent className="px-0 pb-0 pt-6">
        {passwordEnabled && mode !== "forgot" && registrationsEnabled ? (
          <div className="mb-6 flex rounded-md border border-border bg-muted p-1">
            <button
              className={cn(
                "flex-1 rounded-sm px-4 py-2 text-sm font-medium transition-colors",
                mode === "login"
                  ? "bg-background text-foreground shadow-sm"
                  : "text-muted-foreground",
              )}
              onClick={() => switchMode("login")}
              type="button"
            >
              Sign in
            </button>
            <button
              className={cn(
                "flex-1 rounded-sm px-4 py-2 text-sm font-medium transition-colors",
                mode === "register"
                  ? "bg-background text-foreground shadow-sm"
                  : "text-muted-foreground",
              )}
              onClick={() => switchMode("register")}
              type="button"
            >
              Sign up
            </button>
          </div>
        ) : null}

        {mode === "login" && sso ? (
          <div className="mb-6 grid gap-4">
            <Button
              disabled={isPending}
              onClick={() => onSsoSignIn(sso.providerId)}
              size="lg"
              type="button"
              variant="secondary"
            >
              Continue with {sso.providerName}
            </Button>
            {passwordEnabled ? (
              <div className="flex items-center gap-3 text-xs uppercase tracking-wider text-muted-foreground">
                <span className="h-px flex-1 bg-border" />
                or
                <span className="h-px flex-1 bg-border" />
              </div>
            ) : null}
          </div>
        ) : null}

        {error ? (
          <Alert className="mb-4" variant="destructive">
            <AlertDescription>{error}</AlertDescription>
          </Alert>
        ) : null}

        {mode === "forgot" && forgotSent ? (
          <div className="grid gap-4">
            <Alert className="border-emerald-500/30 text-emerald-500">
              <AlertDescription className="text-emerald-500">
                If an account exists for that email, a reset link is on its way.
              </AlertDescription>
            </Alert>
            <Button onClick={() => switchMode("login")} type="button" variant="secondary">
              Back to sign in
            </Button>
          </div>
        ) : passwordEnabled ? (
          <form className="grid gap-4" onSubmit={onSubmit}>
            {mode === "register" ? (
              <Field label="Name">
                <Input name="name" placeholder="Jane Doe" />
              </Field>
            ) : null}

            <Field label="Email">
              <Input name="email" placeholder="jane@company.dev" required type="email" />
            </Field>

            {mode !== "forgot" ? (
              <Field label="Password">
                <Input name="password" required type="password" />
              </Field>
            ) : null}

            {mode === "login" ? (
              <button
                className="justify-self-start text-xs text-muted-foreground underline-offset-4 hover:underline"
                onClick={() => switchMode("forgot")}
                type="button"
              >
                Forgot password?
              </button>
            ) : null}

            <Button className="mt-2" disabled={isPending} size="lg" type="submit">
              {isPending
                ? "Please wait..."
                : mode === "login"
                  ? "Sign in"
                  : mode === "register"
                    ? "Create account"
                    : "Send reset link"}
            </Button>

            {mode === "forgot" ? (
              <Button onClick={() => switchMode("login")} type="button" variant="ghost">
                Back to sign in
              </Button>
            ) : null}
          </form>
        ) : null}
      </CardContent>
    </div>
  );
}

export { AuthHeroPanel, AuthModePanel };
