apiVersion: v2
name: spicytrack
description: Deploy SpicyTrack with external or optionally bundled data services.
type: application
version: 1.0.2
appVersion: "1.0.2"
keywords:
  - error-tracking
  - observability
  - sentry
maintainers:
  - name: SpicyTrack
