export type OrganizationRole = "owner" | "admin" | "manager" | "developer" | "member" | "viewer";

export type Permission =
  | "org.read"
  | "org.members.read"
  | "org.members.invite"
  | "org.members.update_role"
  | "org.members.remove"
  | "org.teams.read"
  | "org.teams.create"
  | "org.teams.update"
  | "org.teams.delete"
  | "org.projects.read"
  | "org.projects.create"
  | "org.projects.update"
  | "project.read"
  | "project.issues.read"
  | "project.issues.manage"
  | "project.events.read"
  | "project.releases.read"
  | "project.releases.manage"
  | "project.artifacts.read"
  | "project.artifacts.manage"
  | "project.alerts.read"
  | "project.alerts.manage"
  | "project.keys.read"
  | "project.keys.manage"
  | "project.integrations.read"
  | "project.integrations.manage"
  | "project.autofix.read"
  | "project.autofix.run"
  | "project.autofix.manage"
  | "org.settings.manage"
  | "org.mcp.manage"
  | "audit.read";
